apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: {{index . "namespace"}}
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 30m
  install:
    remediation:
      retries: 3
  test:
    enable: false
