apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: {{index . "namespace"}}
spec:
  serviceAccountName: {{index . "serviceAccountName"}}
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: "1.3.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  interval: 30m
  install:
    remediation:
      retries: 3
  test:
    enable: false
